### ISSUE TITLE
Barrels opened by other players don't spawn bubbles

### ISSUE THREAD

**Issue by YoshiRulz** [Tschipcraft/fabric_make_bubbles_pop_mod#11]
### Describe the bug

Opening chests or barrels creates bubbles. Watching another player open a chest, I see bubbles, but not with a barrel.

### Steps to reproduce

1. Be in multiplayer
2. Place barrel
3. Have friend click barrel

### Expected behavior

bubble

### Additional context

Using version 0.2.0 of the mod for Fabric on MC 1.20.4.

**Comment by Tschipcraft** [comment]
This is a known issue. AViewFromTheTop has already figured out a solution for the Fabric version (see #7), but I have no idea how to implement this in Forge since it requires custom network packets. It will be in the next release as a Fabric exclusive feature I guess..

_Edit:_ I found a different way to implement this in Forge by registering a clientTick method for the BarrelBlock
